apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: hpa-resource-eater
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-eater-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization #Utilization, Value, or AverageValue
        averageUtilization: 10 #percentage other can averageValue, value
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50 