apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-eater-deployment
  labels:
    app: resource-eater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-eater
  template:
    metadata:
      labels:
        app: resource-eater
    spec:
      containers:
      - name: resource-eater
        image: hemant24/resource-eater:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "300m"


---


apiVersion: v1
kind: Service
metadata:
  name: resource-eater
  namespace: default
spec:
  type: NodePort #LoadBalancer
  selector:
    app: resource-eater
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000